---
title: "Cybersecurity salaries"
output: html_notebook
---


### Problem
We are living in the “information age” or rather the “data age”, meaning that everything around us revolves around data. The data has become one of the most valuable assets that a person or an organisation can have, since it has a significant value, losing it will lead to significant damages. Thus, most of the attacks nowadays are directed toward the data. To guard against such damages, organisations have realised the importance of protecting their digital assets, leading them to hire cybersecurity specialists. This made cybersecurity gain popularity among people so there’s a growing tendency to study cybersecurity. Consequently this resulted in the emergence of plentiful professionals with various experience levels and skills in this field. As a result, organisations may find it difficult to decide a salary for job candidates solely based on the CV. also, since the attacks improve rapidly, organisations need to hire more employees in the far future to defend against such attacks but it’s not an easy matter to predict the future payroll which may hinders some of the organisation's plans. Another issue arises when the decision makers in the organisation aren’t fully aware of the trends on salary. Their lack of awareness gives a chance for the competitor organisations to attract their employees to them by offering a better salary that match current trends



### Goal
Given the problems we discussed and In order to better understand this field, we decided to analyse a dataset of 1247 cybersecurity employees, containing information such as salary, job title, and experience level.  Analysing this dataset can provide insightful predictions regarding the salary range of a cybersecurity employee, which can help in

* Making better decisions
* Making recruitment and hiring process easier and more efficient
* Predicting the future payroll
* Increasing loyalty
* Increasing the satisfaction rate
* Achieving fairness

## Source of data:
https://www.kaggle.com/datasets/deepcontractor/cyber-security-salarie



```{r}
dataset= read.csv(url("https://raw.githubusercontent.com/SarahAlhindi/DM_project/main/Data%20Set/salaries_cyber.csv"), header=TRUE)

```






## General information about the dataset:

No. of attributes: 11  
Type of attributes: Ordinal , Nominal, and Numeric  
No. of objects: 1247  
Class label: salary_in_usd       







<table border=1px solid black>
<tr style="background-color:#D3D3D3">
<th>Attribute Name</th>
<th>Description</th>
<th>Data Type</th> 
<th>Possible values</th>
</tr>

<tr>
<td>work_year</td> 
<td>The year in which salary was recorded</td> 
<td>Numerical</td>
<td>2020 to 2022</td>
</tr>

<tr>
<td>experience_level</td> 
<td>Expertise level of the employee</td> 
<td>Ordinal</td>
<td>En “Entry level” <br> 
MI “Mid level” <br>
SE “Senior level” <br>
EX “Executive level”

</td> 
</tr>


<tr>
<td>employment_type</td> 
<td>Sort of employment</td> 
<td>Nominal</td> 
<td>PT “Part time” <br>
FT “Full time” <br>
CT “Contract <br>
FL “Freelancer”
</td>
</tr>

<tr>
<td>job_title</td> 
<td>The role worked in during the year</td> 
<td>Nominal </td> 
<td>Different titles</td>
</tr>

<tr>
<td>salary</td> 
<td>The total gross salary amount paid</td> 
<td>Numerical</td> 
<td>1740-50001566</td>
</tr>
<tr>
<td>salary_currency</td> 
<td>The currency of the salary paid to the employee</td> 
<td>Nominal</td> 
<td>Different currencies according to ISO 4217 currency code</td>
</tr>

<tr>
<td>salary_in_usd</td> 
<td>The salary paid in United states dollar</td> 
<td>Numerical</td> 
<td>2000 to 365596.40</td>
</tr>

<tr>
<td>employee_residence</td> 
<td>Employee's primary country of residence</td> 
<td>Nominal</td> 
<td>Different countries</td>
</tr>

<tr>
<td>remote_ratio</td> 
<td>Percentage of online work by employee in the specified year</td> 
<td>Numerical</td> 
<td> 0 “No remote work” <br>
50 “Partially remote” <br>
100 “Fully remote”

</td>
</tr>

<tr>
<td>company_location</td> 
<td>The country of the employer's main office</td> 
<td>Nominal</td> 
<td>Different countries</td>
</tr>

<tr>
<td>company_size</td> 
<td>How big/small is the company</td> 
<td>Ordinal</td> 
<td>S , M or L</td>
</tr>

</table>



